### PR TITLE
Index.html Updates

### PR DESCRIPTION
**Pull request by VoltixG**
- Added both Kash445 and Hockeyfan360 to the Assistant Executives as Admin Officers
- Removed Saxsational due to his inactivity post
- Added Wade_Smith to Assistant Executives as Associated Server Liaison
- Added BuscusFan to the Executives as Associated Server Liaison
- Removed BuscusFan from Assistant Executives
- Added StevenNL2000 and Madgeek1450 to Global Moderators
- Added xfilez to Executives and Added Dusty01 to Assistant Executives as Creative Designers
~~- Removed Wade_Smith (CrafterSmith12) due to inactivity (Voluntarily stepped down)~~
~~- Added "Join our Discord" as a title for the Discord widget~~

### CODE REVIEW

**Comment by aggelosQQ** [comment]
Thank you for updating it, but please remove the "Join our Discord" text above the widget, and I will merge.

**Comment by aggelosQQ** [comment]
Okay, I will be going to test the code.

**Comment by ghost** [comment]
Global Forum Moderators no longer exist. They are now Forum Administrators.

**Comment by VoltixG** [comment]
@pramire The website still says "Global Forum Moderators"
`<h2 class="rank">Global Forum Moderators</h2>`

**Pull request merged**
